### ISSUE TITLE
Potential false negative: misuse-of-free

### ISSUE THREAD

**Issue by evintila** [GJDuck/RedFat#1]
Dear RedFat authors,

We have noticed that RedFat does not detect some misuses of free (CWE-761), and are wondering if this is expected behavior.

The misuse (freeing a stack pointer) in the following example is not detected:

```C
#include <stdlib.h>

int main()
{
  unsigned long stack_object[20];
  stack_object[1] = 0x20;
  free(&stack_object[2]);

  return 0;
}
```

Version used:

```
RedFat 0.3.0 (prebuilt)
```

We compiled the code with clang:

```
clang version 19.1.0-rc4 (https://github.com/llvm/llvm-project.git f0010d131b79a1b401777aa32e96defc4a935c9d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

Commands used:

```bash
clang ./misuse_of_free.c
redfat -Xreads -Xadjust -Oglobal=false -Ostack=false -Obatch=1 -Omerge=false ./a.out -o ./a.out.redfat
LD_PRELOAD=/usr/share/redfat/libredfat.so ./a.out.redfat
```

**Comment by GJDuck** [comment]
This is expected behavior.

Basically, the RedFat allocator can only check for errors on RedFat-allocated objects.  It cannot check for errors on non-RedFat-allocated pointers, since it has no knowledge about these pointers.

In fact, for compatibility, RedFat-`free()` will forward non-RedFat pointers to the underlying libc `free()`, to handle the common case where a libc-allocated pointer is passed to RedFat-`free()`.  The runtime could be easily changed to report this as an error, but this will break compatibility with most programs.

Since the example program passes non-RedFat-allocated pointer to RedFat-`free()`, there is no error checking.  But this is expected behavior, and necessary for compatibility.  RedFat only checks for errors on RedFat-allocated objects.
